/**
 * Reachability repository: tokenised inbound-call grants (reachability_channels) and
 * shareable contact links (contact_shares, permanent or single-/limited-use). Channel
 * tokens are generated by the DB default; share tokens are generated here.
 */
import crypto from 'crypto';
import {
  db,
  reachabilityChannels,
  channelUsageLog,
  contactShares,
  shareEvents,
  users,
  eq,
  and,
  or,
  gt,
  isNull,
  sql,
  desc,
} from '@trustroute/core';

export type ChannelRow = typeof reachabilityChannels.$inferSelect;
export type ShareRow = typeof contactShares.$inferSelect;

const shareToken = () => crypto.randomBytes(24).toString('base64url');

// ── Reachability channels ─────────────────────────────────────────────────────

export async function createChannel(
  ownerId: string,
  input: { label?: string | null; dailyLimit?: number; totalLimit?: number | null; expiresAt?: Date | null },
): Promise<ChannelRow> {
  const [row] = await db
    .insert(reachabilityChannels)
    .values({
      ownerId,
      label: input.label ?? null,
      dailyLimit: input.dailyLimit ?? 3,
      totalLimit: input.totalLimit ?? null,
      expiresAt: input.expiresAt ?? null,
    })
    .returning();
  return row!;
}

export async function listChannels(ownerId: string): Promise<ChannelRow[]> {
  return db
    .select()
    .from(reachabilityChannels)
    .where(eq(reachabilityChannels.ownerId, ownerId))
    .orderBy(desc(reachabilityChannels.createdAt));
}

export async function revokeChannel(ownerId: string, channelId: string): Promise<boolean> {
  const rows = await db
    .update(reachabilityChannels)
    .set({ status: 'revoked', updatedAt: sql`now()` })
    .where(and(eq(reachabilityChannels.channelId, channelId), eq(reachabilityChannels.ownerId, ownerId)))
    .returning({ id: reachabilityChannels.channelId });
  return rows.length > 0;
}

/** Resolve an inbound token to its (active, unexpired) channel + owner. */
export async function findActiveChannelByToken(token: string) {
  const [row] = await db
    .select({
      channel: reachabilityChannels,
      owner: {
        userId: users.userId,
        handle: users.handle,
        displayName: users.displayName,
        avatarUrl: users.avatarUrl,
        trustTier: users.trustTier,
      },
    })
    .from(reachabilityChannels)
    .innerJoin(users, eq(users.userId, reachabilityChannels.ownerId))
    .where(
      and(
        eq(reachabilityChannels.token, token),
        eq(reachabilityChannels.status, 'active'),
        or(isNull(reachabilityChannels.expiresAt), gt(reachabilityChannels.expiresAt, sql`now()`)),
      ),
    )
    .limit(1);
  return row ?? null;
}

export async function logChannelUse(
  channelId: string,
  callerId: string | null,
  action: string,
  metadata: Record<string, unknown> = {},
): Promise<void> {
  await db.transaction(async (tx) => {
    await tx.insert(channelUsageLog).values({ channelId, callerId, action, metadata });
    await tx
      .update(reachabilityChannels)
      .set({ useCount: sql`${reachabilityChannels.useCount} + 1`, updatedAt: sql`now()` })
      .where(eq(reachabilityChannels.channelId, channelId));
  });
}

// ── Contact shares (QR / link) ────────────────────────────────────────────────

export async function createShare(
  ownerId: string,
  input: { type: 'permanent' | 'disposable'; label?: string | null; expiresAt?: Date | null; maxUses?: number | null },
): Promise<ShareRow> {
  const [row] = await db
    .insert(contactShares)
    .values({
      ownerId,
      token: shareToken(),
      type: input.type,
      label: input.label ?? null,
      expiresAt: input.expiresAt ?? null,
      maxUses: input.maxUses ?? (input.type === 'disposable' ? 1 : null),
    })
    .returning();
  return row!;
}

export async function listShares(ownerId: string): Promise<ShareRow[]> {
  return db
    .select()
    .from(contactShares)
    .where(and(eq(contactShares.ownerId, ownerId), eq(contactShares.active, true)))
    .orderBy(desc(contactShares.createdAt));
}

export async function revokeShare(ownerId: string, shareId: string): Promise<boolean> {
  const rows = await db
    .update(contactShares)
    .set({ active: false, revokedAt: sql`now()` })
    .where(and(eq(contactShares.shareId, shareId), eq(contactShares.ownerId, ownerId)))
    .returning({ id: contactShares.shareId });
  return rows.length > 0;
}

export async function findActiveShareByToken(token: string) {
  const [row] = await db
    .select({
      share: contactShares,
      owner: {
        userId: users.userId,
        handle: users.handle,
        displayName: users.displayName,
        avatarUrl: users.avatarUrl,
        trustTier: users.trustTier,
        discoveryShowTrustScore: users.discoveryShowTrustScore,
        trustScore: users.trustScore,
      },
    })
    .from(contactShares)
    .innerJoin(users, eq(users.userId, contactShares.ownerId))
    .where(
      and(
        eq(contactShares.token, token),
        eq(contactShares.active, true),
        or(isNull(contactShares.expiresAt), gt(contactShares.expiresAt, sql`now()`)),
      ),
    )
    .limit(1);
  return row ?? null;
}

/**
 * Record a scan atomically: append the event, bump `uses`, and deactivate the share
 * once its `max_uses` is exhausted. Returns false if the share was already spent.
 */
export async function recordScan(
  shareId: string,
  scannerId: string | null,
  deviceHash: string | null,
): Promise<boolean> {
  return db.transaction(async (tx) => {
    const [share] = await tx
      .update(contactShares)
      .set({
        uses: sql`${contactShares.uses} + 1`,
        active: sql`CASE WHEN ${contactShares.maxUses} IS NOT NULL AND ${contactShares.uses} + 1 >= ${contactShares.maxUses} THEN FALSE ELSE ${contactShares.active} END`,
      })
      .where(
        and(
          eq(contactShares.shareId, shareId),
          eq(contactShares.active, true),
          or(isNull(contactShares.maxUses), sql`${contactShares.uses} < ${contactShares.maxUses}`),
        ),
      )
      .returning({ id: contactShares.shareId });
    if (!share) return false;
    await tx.insert(shareEvents).values({ shareId, scannerId, deviceHash });
    return true;
  });
}
